name: boundless-media-server
services:
  - dockerfile_path: Dockerfile
    github:
      branch: master
      deploy_on_push: true
      repo: kirill-zhirnov/media-server
    name: node
    http_port: 3010
    cors:
      allow_origins:
        - regex: .*
      allow_methods:
        - get
      max_age: 3600
      allow_credentials: true