services:
  node:
    build:
      context: ../
      dockerfile: ./.docker/node-prod.Dockerfile
    restart: always
    volumes:
      - type: bind
        source: "${DOCKER_CACHE_VOLUME}"
        target: /home/node/external_runtime

  nginx:
    build:
      context: ../
      dockerfile: ./.docker/nginx-prod.Dockerfile
      args:
        DOCKER_NGINX_NODE_HOST: ${DOCKER_NGINX_NODE_HOST:-node}
    restart: always
    ports:
      - "${DOCKER_NGINX_OUT_PORT:-8080}:80"
    depends_on:
      - node

#volumes:
#  cache-volume: