services:
  node:
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
    restart: always
    volumes:
      - type: bind
        source: "${DOCKER_CACHE_VOLUME}"
        target: /home/node/external_runtime

  nginx:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node

#volumes:
#  cache-volume: