services:
  node:
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
    restart: always

  nginx:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node
