services:
  node:
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
    restart: always

  nginx:
    image: nginx:mainline-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
