services:
  node:
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
    restart: always
#    init: true
#    ports:
#      - "3010:3010"

  nginx:
    image: nginx:mainline-alpine
    ports:
      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node
