name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Node resizer
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./.docker/node.Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/boundless-s3-resizer:latest

